"""Phase 35 observation accounting contracts.

Read-only lifecycle funnel over immutable records. Answers: why do we
currently have N real paired observations — without inspecting the DB.
"""
from __future__ import annotations

OBSERVATION_CONTRACT_VERSION = "OBSERVATION_ACCOUNTING_V1"

# Lifecycle stages (§22).
STAGE_DISCOVERED = "DISCOVERED"
STAGE_ELIGIBLE = "ELIGIBLE"
STAGE_PREDICTED = "PREDICTED"
STAGE_SHADOWED = "SHADOWED"
STAGE_FINISHED = "FINISHED"
STAGE_OUTCOME_VERIFIED = "OUTCOME_VERIFIED"
STAGE_EVALUATED = "EVALUATED"
STAGE_PAIRED = "PAIRED"
STAGE_INCLUDED = "INCLUDED_IN_EVIDENCE"

# Exclusion reasons (existing taxonomy reused where possible).
EXCLUDE_NO_READINESS = "NO_READINESS"
EXCLUDE_READINESS_BLOCKED = "READINESS_BLOCKED"
EXCLUDE_INSUFFICIENT_HISTORY = "INSUFFICIENT_HISTORY"
EXCLUDE_PROVIDER_INACTIVE = "PROVIDER_INACTIVE"
EXCLUDE_DUPLICATE = "DUPLICATE"
EXCLUDE_POST_CUTOFF = "POST_CUTOFF"
EXCLUDE_MISSING_OUTCOME = "MISSING_OUTCOME"
EXCLUDE_INVALID_PAIR = "INVALID_PAIR"
EXCLUDE_NOT_EVALUATED = "NOT_EVALUATED"
EXCLUDE_NO_SHADOW = "NO_SHADOW"
EXCLUDE_PENDING_OUTCOME = "PENDING_OUTCOME"
