"""production schema complete

Revision ID: 0009_production_schema_complete
Revises: 0008_training_runs
Create Date: 2026-09-19 16:03:07.979572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0009_production_schema_complete'
down_revision = '0008_training_runs'
branch_labels = None
depends_on = None



def _safe_create_table(name, *columns, **kwargs):
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if name not in insp.get_table_names():
        op.create_table(name, *columns, **kwargs)

def _safe_create_index(index_name, table_name, columns, **kwargs):
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if table_name in insp.get_table_names():
        existing = [idx['name'] for idx in insp.get_indexes(table_name)]
        if index_name not in existing:
            try:
                op.create_index(index_name, table_name, columns, **kwargs)
            except (sa.exc.OperationalError, sa.exc.ProgrammingError) as exc:
                msg = str(exc).lower()
                if "already exists" not in msg and "duplicate" not in msg:
                    raise

def _safe_drop_index(index_name, table_name=None, **kwargs):
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if table_name and table_name in insp.get_table_names():
        existing = [idx['name'] for idx in insp.get_indexes(table_name)]
        if index_name in existing:
            try:
                op.drop_index(index_name, table_name=table_name, **kwargs)
            except (sa.exc.OperationalError, sa.exc.ProgrammingError) as exc:
                msg = str(exc).lower()
                if "does not exist" not in msg and "not found" not in msg:
                    raise

def _safe_drop_table(name, **kwargs):
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if name in insp.get_table_names():
        try:
            op.drop_table(name, **kwargs)
        except (sa.exc.OperationalError, sa.exc.ProgrammingError) as exc:
            msg = str(exc).lower()
            if "does not exist" not in msg and "not found" not in msg:
                raise

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _safe_create_table('acquisition_job_locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lock_key', sa.String(length=128), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('competition', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index(op.f('ix_acquisition_job_locks_lock_key'), 'acquisition_job_locks', ['lock_key'], unique=True)
    _safe_create_table('acquisition_job_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=128), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('competition', sa.String(length=32), nullable=False),
    sa.Column('season', sa.String(length=32), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('plan_hash', sa.String(length=64), nullable=False),
    sa.Column('qualification_hash', sa.String(length=64), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('new_observations', sa.Integer(), nullable=False),
    sa.Column('duplicate_observations', sa.Integer(), nullable=False),
    sa.Column('new_matches', sa.Integer(), nullable=False),
    sa.Column('updated_matches', sa.Integer(), nullable=False),
    sa.Column('unresolved_identities', sa.Integer(), nullable=False),
    sa.Column('conflicts', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=128), nullable=False),
    sa.Column('error_message', sa.String(length=512), nullable=False),
    sa.Column('dry_run', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index('ix_acq_job_records_competition', 'acquisition_job_records', ['competition', 'job_type'], unique=False)
    _safe_create_index('ix_acq_job_records_type_status', 'acquisition_job_records', ['job_type', 'status'], unique=False)
    _safe_create_index(op.f('ix_acquisition_job_records_competition'), 'acquisition_job_records', ['competition'], unique=False)
    _safe_create_index(op.f('ix_acquisition_job_records_job_id'), 'acquisition_job_records', ['job_id'], unique=False)
    _safe_create_index(op.f('ix_acquisition_job_records_job_type'), 'acquisition_job_records', ['job_type'], unique=False)
    _safe_create_index(op.f('ix_acquisition_job_records_source'), 'acquisition_job_records', ['source'], unique=False)
    _safe_create_index(op.f('ix_acquisition_job_records_status'), 'acquisition_job_records', ['status'], unique=False)
    _safe_create_table('acquisition_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('last_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index(op.f('ix_acquisition_jobs_name'), 'acquisition_jobs', ['name'], unique=True)
    _safe_create_table('acquisition_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('job', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_scope', sa.JSON(), nullable=True),
    sa.Column('records_seen', sa.Integer(), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_rejected', sa.Integer(), nullable=False),
    sa.Column('records_quarantined', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index('ix_acq_runs_source_started', 'acquisition_runs', ['source', 'started_at'], unique=False)
    _safe_create_index(op.f('ix_acquisition_runs_run_id'), 'acquisition_runs', ['run_id'], unique=False)
    _safe_create_index(op.f('ix_acquisition_runs_source'), 'acquisition_runs', ['source'], unique=False)
    _safe_create_index(op.f('ix_acquisition_runs_status'), 'acquisition_runs', ['status'], unique=False)
    _safe_create_table('canonical_field_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('canonical_entity_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.String(length=512), nullable=True),
    sa.Column('new_value', sa.String(length=512), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index('ix_canon_version_entity', 'canonical_field_versions', ['entity_type', 'canonical_entity_id', 'field'], unique=False)
    _safe_create_index(op.f('ix_canonical_field_versions_canonical_entity_id'), 'canonical_field_versions', ['canonical_entity_id'], unique=False)
    _safe_create_index(op.f('ix_canonical_field_versions_entity_type'), 'canonical_field_versions', ['entity_type'], unique=False)
    _safe_create_table('manual_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_record_id', sa.String(length=128), nullable=False),
    sa.Column('canonical_entity_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index(op.f('ix_manual_mappings_canonical_entity_id'), 'manual_mappings', ['canonical_entity_id'], unique=False)
    _safe_create_index(op.f('ix_manual_mappings_entity_type'), 'manual_mappings', ['entity_type'], unique=False)
    _safe_create_table('reconciliation_conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('canonical_entity_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('source_a', sa.String(length=64), nullable=False),
    sa.Column('source_b', sa.String(length=64), nullable=False),
    sa.Column('value_a', sa.String(length=512), nullable=True),
    sa.Column('value_b', sa.String(length=512), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('resolution_status', sa.String(length=32), nullable=False),
    sa.Column('resolved_by', sa.String(length=64), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dedup_key', sa.String(length=128), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index('ix_recon_conflict_entity', 'reconciliation_conflicts', ['entity_type', 'canonical_entity_id'], unique=False)
    _safe_create_index(op.f('ix_reconciliation_conflicts_canonical_entity_id'), 'reconciliation_conflicts', ['canonical_entity_id'], unique=False)
    _safe_create_index(op.f('ix_reconciliation_conflicts_dedup_key'), 'reconciliation_conflicts', ['dedup_key'], unique=False)
    _safe_create_index(op.f('ix_reconciliation_conflicts_entity_type'), 'reconciliation_conflicts', ['entity_type'], unique=False)
    _safe_create_index(op.f('ix_reconciliation_conflicts_resolution_status'), 'reconciliation_conflicts', ['resolution_status'], unique=False)
    _safe_create_index(op.f('ix_reconciliation_conflicts_severity'), 'reconciliation_conflicts', ['severity'], unique=False)
    _safe_create_table('research_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('feature_version', sa.String(length=32), nullable=False),
    sa.Column('dataset_version', sa.String(length=64), nullable=False),
    sa.Column('training_period', sa.String(length=64), nullable=False),
    sa.Column('validation_period', sa.String(length=64), nullable=False),
    sa.Column('test_period', sa.String(length=64), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('artifact_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index(op.f('ix_research_models_artifact_hash'), 'research_models', ['artifact_hash'], unique=False)
    _safe_create_index(op.f('ix_research_models_model_id'), 'research_models', ['model_id'], unique=False)
    _safe_create_index(op.f('ix_research_models_status'), 'research_models', ['status'], unique=False)
    _safe_create_table('source_activations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index(op.f('ix_source_activations_source'), 'source_activations', ['source'], unique=False)
    _safe_create_index(op.f('ix_source_activations_state'), 'source_activations', ['state'], unique=False)
    _safe_create_table('source_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('last_success', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('records_received', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('quota_remaining', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(length=512), nullable=False),
    sa.Column('last_http_status', sa.Integer(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('backoff_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_response_bytes', sa.Integer(), nullable=True),
    sa.Column('last_fixture_count', sa.Integer(), nullable=True),
    sa.Column('last_qualification', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index(op.f('ix_source_health_source'), 'source_health', ['source'], unique=True)
    _safe_create_index('ix_source_health_source_fetched', 'source_health', ['source', 'updated_at'], unique=False)
    _safe_create_index(op.f('ix_source_health_state'), 'source_health', ['state'], unique=False)
    _safe_create_table('source_qualifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qualification_run_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('competition', sa.String(length=32), nullable=False),
    sa.Column('season', sa.String(length=16), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('response_count', sa.Integer(), nullable=False),
    sa.Column('fixture_count', sa.Integer(), nullable=False),
    sa.Column('resolved_count', sa.Integer(), nullable=False),
    sa.Column('unresolved_count', sa.Integer(), nullable=False),
    sa.Column('conflict_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=True),
    sa.Column('capability_hash', sa.String(length=64), nullable=False),
    sa.Column('sample_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index(op.f('ix_source_qualifications_qualification_run_id'), 'source_qualifications', ['qualification_run_id'], unique=False)
    _safe_create_index(op.f('ix_source_qualifications_source'), 'source_qualifications', ['source'], unique=False)
    _safe_create_index(op.f('ix_source_qualifications_status'), 'source_qualifications', ['status'], unique=False)
    _safe_create_table('stat_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('provider_definition', sa.String(length=512), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('aggregation', sa.String(length=64), nullable=False),
    sa.Column('canonical_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index(op.f('ix_stat_definitions_metric_name'), 'stat_definitions', ['metric_name'], unique=False)
    _safe_create_index(op.f('ix_stat_definitions_source'), 'stat_definitions', ['source'], unique=False)
    _safe_create_table('unresolved_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_record_id', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('dedup_key', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index(op.f('ix_unresolved_records_dedup_key'), 'unresolved_records', ['dedup_key'], unique=False)
    _safe_create_index(op.f('ix_unresolved_records_entity_type'), 'unresolved_records', ['entity_type'], unique=False)
    _safe_create_index(op.f('ix_unresolved_records_status'), 'unresolved_records', ['status'], unique=False)
    _safe_create_table('match_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('raw_reference', sa.String(length=128), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('previous_value', sa.String(length=256), nullable=True),
    sa.Column('new_value', sa.String(length=256), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index('ix_match_obs_match_field', 'match_observations', ['match_id', 'field'], unique=False)
    _safe_create_index(op.f('ix_match_observations_match_id'), 'match_observations', ['match_id'], unique=False)
    _safe_create_index(op.f('ix_match_observations_source'), 'match_observations', ['source'], unique=False)
    _safe_create_table('mirofish_scenario_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('intelligence_snapshot_id', sa.String(length=64), nullable=True),
    sa.Column('contract_version', sa.String(length=64), nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('scenario_hash', sa.String(length=64), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_hash', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_payload', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index(op.f('ix_mirofish_scenario_runs_intelligence_snapshot_id'), 'mirofish_scenario_runs', ['intelligence_snapshot_id'], unique=False)
    _safe_create_index(op.f('ix_mirofish_scenario_runs_match_id'), 'mirofish_scenario_runs', ['match_id'], unique=False)
    _safe_create_index(op.f('ix_mirofish_scenario_runs_request_hash'), 'mirofish_scenario_runs', ['request_hash'], unique=False)
    _safe_create_index(op.f('ix_mirofish_scenario_runs_scenario_id'), 'mirofish_scenario_runs', ['scenario_id'], unique=False)
    _safe_create_index(op.f('ix_mirofish_scenario_runs_status'), 'mirofish_scenario_runs', ['status'], unique=False)
    _safe_create_table('player_feature_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('cutoff', sa.DateTime(timezone=True), nullable=True),
    sa.Column('feature_version', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index(op.f('ix_player_feature_snapshots_match_id'), 'player_feature_snapshots', ['match_id'], unique=False)
    _safe_create_index(op.f('ix_player_feature_snapshots_payload_hash'), 'player_feature_snapshots', ['payload_hash'], unique=False)
    _safe_create_index('ix_player_snap_match_cutoff', 'player_feature_snapshots', ['match_id', 'cutoff'], unique=False)
    _safe_create_table('player_team_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index('ix_membership_player_team', 'player_team_memberships', ['player_id', 'team_id'], unique=False)
    _safe_create_index(op.f('ix_player_team_memberships_player_id'), 'player_team_memberships', ['player_id'], unique=False)
    _safe_create_index(op.f('ix_player_team_memberships_team_id'), 'player_team_memberships', ['team_id'], unique=False)
    _safe_create_table('analogue_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('feature_version', sa.String(length=32), nullable=False),
    sa.Column('cutoff', sa.DateTime(timezone=True), nullable=True),
    sa.Column('temporal_mode', sa.String(length=32), nullable=False),
    sa.Column('calculation_version', sa.String(length=64), nullable=False),
    sa.Column('input_reference', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index(op.f('ix_analogue_results_match_id'), 'analogue_results', ['match_id'], unique=False)
    _safe_create_index(op.f('ix_analogue_results_prediction_id'), 'analogue_results', ['prediction_id'], unique=False)
    _safe_create_index(op.f('ix_analogue_results_status'), 'analogue_results', ['status'], unique=False)
    _safe_create_table('intelligence_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('feature_version', sa.String(length=32), nullable=False),
    sa.Column('dataset_version', sa.String(length=64), nullable=False),
    sa.Column('market_snapshot_version', sa.String(length=64), nullable=False),
    sa.Column('cutoff', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index(op.f('ix_intelligence_snapshots_match_id'), 'intelligence_snapshots', ['match_id'], unique=False)
    _safe_create_index(op.f('ix_intelligence_snapshots_payload_hash'), 'intelligence_snapshots', ['payload_hash'], unique=False)
    _safe_create_index(op.f('ix_intelligence_snapshots_snapshot_id'), 'intelligence_snapshots', ['snapshot_id'], unique=False)
    _safe_create_table('mirofish_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('feature_version', sa.String(length=32), nullable=False),
    sa.Column('cutoff', sa.DateTime(timezone=True), nullable=True),
    sa.Column('temporal_mode', sa.String(length=32), nullable=False),
    sa.Column('calculation_version', sa.String(length=64), nullable=False),
    sa.Column('input_reference', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('scenario_seed', sa.Integer(), nullable=True),
    sa.Column('mirofish_version', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index(op.f('ix_mirofish_runs_match_id'), 'mirofish_runs', ['match_id'], unique=False)
    _safe_create_index(op.f('ix_mirofish_runs_prediction_id'), 'mirofish_runs', ['prediction_id'], unique=False)
    _safe_create_index(op.f('ix_mirofish_runs_status'), 'mirofish_runs', ['status'], unique=False)
    _safe_create_table('player_feature_provenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_record_ids', sa.JSON(), nullable=True),
    sa.Column('canonical_ids', sa.JSON(), nullable=True),
    sa.Column('quality', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['player_feature_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index(op.f('ix_player_feature_provenance_feature_name'), 'player_feature_provenance', ['feature_name'], unique=False)
    _safe_create_index(op.f('ix_player_feature_provenance_snapshot_id'), 'player_feature_provenance', ['snapshot_id'], unique=False)
    _safe_create_table('prediction_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('actual_home_goals', sa.Integer(), nullable=True),
    sa.Column('actual_away_goals', sa.Integer(), nullable=True),
    sa.Column('actual_result', sa.String(length=16), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index(op.f('ix_prediction_evaluations_match_id'), 'prediction_evaluations', ['match_id'], unique=False)
    _safe_create_index(op.f('ix_prediction_evaluations_prediction_id'), 'prediction_evaluations', ['prediction_id'], unique=True)
    _safe_create_table('prediction_explanations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('feature_version', sa.String(length=32), nullable=False),
    sa.Column('cutoff', sa.DateTime(timezone=True), nullable=True),
    sa.Column('temporal_mode', sa.String(length=32), nullable=False),
    sa.Column('calculation_version', sa.String(length=64), nullable=False),
    sa.Column('input_reference', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index(op.f('ix_prediction_explanations_match_id'), 'prediction_explanations', ['match_id'], unique=False)
    _safe_create_index(op.f('ix_prediction_explanations_prediction_id'), 'prediction_explanations', ['prediction_id'], unique=False)
    _safe_create_index(op.f('ix_prediction_explanations_status'), 'prediction_explanations', ['status'], unique=False)
    _safe_create_table('prediction_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('feature_version', sa.String(length=32), nullable=False),
    sa.Column('calibration_version', sa.String(length=64), nullable=False),
    sa.Column('scenario_version', sa.String(length=64), nullable=False),
    sa.Column('derived_market_version', sa.String(length=64), nullable=False),
    sa.Column('cutoff', sa.DateTime(timezone=True), nullable=True),
    sa.Column('market_snapshot_ids', sa.JSON(), nullable=True),
    sa.Column('feature_snapshot_ref', sa.String(length=128), nullable=False),
    sa.Column('input_reference', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index('ix_prediction_versions_match_created', 'prediction_versions', ['match_id', 'created_at'], unique=False)
    _safe_create_index('ix_prediction_versions_match_cutoff', 'prediction_versions', ['match_id', 'cutoff'], unique=False)
    _safe_create_index(op.f('ix_prediction_versions_match_id'), 'prediction_versions', ['match_id'], unique=False)
    _safe_create_index(op.f('ix_prediction_versions_prediction_id'), 'prediction_versions', ['prediction_id'], unique=False)
    _safe_create_index(op.f('ix_prediction_versions_state'), 'prediction_versions', ['state'], unique=False)
    _safe_create_table('scenario_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('feature_version', sa.String(length=32), nullable=False),
    sa.Column('cutoff', sa.DateTime(timezone=True), nullable=True),
    sa.Column('temporal_mode', sa.String(length=32), nullable=False),
    sa.Column('calculation_version', sa.String(length=64), nullable=False),
    sa.Column('input_reference', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index(op.f('ix_scenario_runs_match_id'), 'scenario_runs', ['match_id'], unique=False)
    _safe_create_index(op.f('ix_scenario_runs_prediction_id'), 'scenario_runs', ['prediction_id'], unique=False)
    _safe_create_index(op.f('ix_scenario_runs_status'), 'scenario_runs', ['status'], unique=False)
    _safe_create_table('prediction_diffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('from_version_id', sa.Integer(), nullable=True),
    sa.Column('to_version_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['from_version_id'], ['prediction_versions.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['to_version_id'], ['prediction_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index(op.f('ix_prediction_diffs_match_id'), 'prediction_diffs', ['match_id'], unique=False)
    _safe_drop_index(op.f('ix_backtest_runs_model'), table_name='backtest_runs')
    _safe_create_index(op.f('ix_backtest_runs_model_name'), 'backtest_runs', ['model_name'], unique=False)
    _safe_drop_index(op.f('ix_sync_provider'), table_name='data_sync_logs')
    _safe_create_index(op.f('ix_data_sync_logs_provider'), 'data_sync_logs', ['provider'], unique=False)
    _safe_drop_index(op.f('ix_leagues_code'), table_name='leagues')
    _safe_create_index(op.f('ix_leagues_code'), 'leagues', ['code'], unique=True)
    _safe_drop_index(op.f('ix_lineups_match'), table_name='lineups')
    _safe_create_index(op.f('ix_lineups_match_id'), 'lineups', ['match_id'], unique=False)
    _safe_drop_index(op.f('ix_match_events_match'), table_name='match_events')
    _safe_create_index(op.f('ix_match_events_match_id'), 'match_events', ['match_id'], unique=False)
    _safe_drop_index(op.f('ix_match_mapping_match'), table_name='match_source_mappings')
    _safe_drop_index(op.f('ix_match_mapping_source'), table_name='match_source_mappings')
    _safe_create_index(op.f('ix_match_source_mappings_match_id'), 'match_source_mappings', ['match_id'], unique=False)
    _safe_create_index(op.f('ix_match_source_mappings_source'), 'match_source_mappings', ['source'], unique=False)
    _safe_drop_index(op.f('ix_match_statistics_match'), table_name='match_statistics')
    _safe_create_index(op.f('ix_match_statistics_match_id'), 'match_statistics', ['match_id'], unique=False)
    _safe_drop_index(op.f('ix_matches_kickoff'), table_name='matches')
    _safe_create_index(op.f('ix_matches_kickoff_at'), 'matches', ['kickoff_at'], unique=False)
    _safe_drop_index(op.f('ix_model_evaluations_model'), table_name='model_evaluations')
    _safe_create_index(op.f('ix_model_evaluations_model_name'), 'model_evaluations', ['model_name'], unique=False)
    _safe_create_index(op.f('ix_model_evaluations_training_run_id'), 'model_evaluations', ['training_run_id'], unique=False)
    _safe_drop_index(op.f('ix_training_runs_model'), table_name='model_training_runs')
    _safe_create_index(op.f('ix_model_training_runs_model_name'), 'model_training_runs', ['model_name'], unique=False)
    _safe_drop_index(op.f('ix_odds_selections_snap'), table_name='odds_selections')
    _safe_create_index(op.f('ix_odds_selections_dedup_hash'), 'odds_selections', ['dedup_hash'], unique=True)
    _safe_create_index(op.f('ix_odds_selections_snapshot_id'), 'odds_selections', ['snapshot_id'], unique=False)
    _safe_drop_index(op.f('ix_odds_snapshots_match'), table_name='odds_snapshots')
    _safe_drop_index(op.f('ix_odds_snapshots_match_bookmaker_market'), table_name='odds_snapshots')
    _safe_drop_index(op.f('ix_odds_snapshots_match_market_time'), table_name='odds_snapshots')
    _safe_drop_index(op.f('ix_odds_snapshots_ts'), table_name='odds_snapshots')
    _safe_create_index(op.f('ix_odds_snapshots_market_type'), 'odds_snapshots', ['market_type'], unique=False)
    _safe_create_index(op.f('ix_odds_snapshots_match_id'), 'odds_snapshots', ['match_id'], unique=False)
    _safe_create_index(op.f('ix_odds_snapshots_timestamp'), 'odds_snapshots', ['timestamp'], unique=False)
    _safe_drop_index(op.f('ix_player_mapping_norm'), table_name='player_provider_mappings')
    _safe_drop_index(op.f('ix_player_mapping_player'), table_name='player_provider_mappings')
    _safe_drop_index(op.f('ix_player_mapping_source'), table_name='player_provider_mappings')
    _safe_create_index(op.f('ix_player_provider_mappings_normalized_name'), 'player_provider_mappings', ['normalized_name'], unique=False)
    _safe_create_index(op.f('ix_player_provider_mappings_player_id'), 'player_provider_mappings', ['player_id'], unique=False)
    _safe_create_index(op.f('ix_player_provider_mappings_source'), 'player_provider_mappings', ['source'], unique=False)
    _safe_create_index(op.f('ix_player_provider_mappings_team_id'), 'player_provider_mappings', ['team_id'], unique=False)
    _safe_create_index(op.f('ix_prediction_results_prediction_id'), 'prediction_results', ['prediction_id'], unique=False)
    _safe_drop_index(op.f('ix_predictions_match'), table_name='predictions')
    _safe_drop_index(op.f('ix_predictions_model'), table_name='predictions')
    _safe_create_index(op.f('ix_predictions_match_id'), 'predictions', ['match_id'], unique=False)
    _safe_create_index(op.f('ix_predictions_model_name'), 'predictions', ['model_name'], unique=False)
    _safe_create_index(op.f('ix_predictions_prediction_timestamp'), 'predictions', ['prediction_timestamp'], unique=False)
    _safe_drop_index(op.f('ix_reqlog_provider'), table_name='provider_request_logs')
    _safe_drop_index(op.f('ix_reqlog_ts'), table_name='provider_request_logs')
    _safe_create_index(op.f('ix_provider_request_logs_provider'), 'provider_request_logs', ['provider'], unique=False)
    _safe_create_index(op.f('ix_provider_request_logs_timestamp'), 'provider_request_logs', ['timestamp'], unique=False)
    _safe_drop_index(op.f('ix_raw_entity'), table_name='raw_data_records')
    _safe_drop_index(op.f('ix_raw_retrieved'), table_name='raw_data_records')
    _safe_drop_index(op.f('ix_raw_source'), table_name='raw_data_records')
    _safe_drop_index(op.f('ix_raw_status'), table_name='raw_data_records')
    _safe_drop_index(op.f('ix_raw_temporal'), table_name='raw_data_records')
    _safe_create_index(op.f('ix_raw_data_records_entity_type'), 'raw_data_records', ['entity_type'], unique=False)
    _safe_create_index(op.f('ix_raw_data_records_processing_status'), 'raw_data_records', ['processing_status'], unique=False)
    _safe_create_index(op.f('ix_raw_data_records_retrieved_at'), 'raw_data_records', ['retrieved_at'], unique=False)
    _safe_create_index(op.f('ix_raw_data_records_source'), 'raw_data_records', ['source'], unique=False)
    _safe_create_index(op.f('ix_raw_data_records_temporal_quality'), 'raw_data_records', ['temporal_quality'], unique=False)
    _safe_drop_index(op.f('ix_conflict_match'), table_name='source_conflicts')
    _safe_drop_index(op.f('ix_conflict_status'), table_name='source_conflicts')
    _safe_create_index(op.f('ix_source_conflicts_match_id'), 'source_conflicts', ['match_id'], unique=False)
    _safe_create_index(op.f('ix_source_conflicts_status'), 'source_conflicts', ['status'], unique=False)
    _safe_drop_index(op.f('ix_standings_league'), table_name='standings')
    _safe_create_index(op.f('ix_standings_league_id'), 'standings', ['league_id'], unique=False)
    _safe_create_index(op.f('ix_standings_team_id'), 'standings', ['team_id'], unique=False)
    _safe_drop_index(op.f('ix_team_mapping_norm'), table_name='team_provider_mappings')
    _safe_drop_index(op.f('ix_team_mapping_source'), table_name='team_provider_mappings')
    _safe_drop_index(op.f('ix_team_mapping_team'), table_name='team_provider_mappings')
    _safe_create_index(op.f('ix_team_provider_mappings_normalized_name'), 'team_provider_mappings', ['normalized_name'], unique=False)
    _safe_create_index(op.f('ix_team_provider_mappings_source'), 'team_provider_mappings', ['source'], unique=False)
    _safe_create_index(op.f('ix_team_provider_mappings_team_id'), 'team_provider_mappings', ['team_id'], unique=False)
    _safe_drop_index(op.f('ix_team_statistics_team'), table_name='team_statistics')
    _safe_create_index(op.f('ix_team_statistics_team_id'), 'team_statistics', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _safe_drop_index(op.f('ix_team_statistics_team_id'), table_name='team_statistics')
    _safe_create_index(op.f('ix_team_statistics_team'), 'team_statistics', ['team_id'], unique=False)
    _safe_drop_index(op.f('ix_team_provider_mappings_team_id'), table_name='team_provider_mappings')
    _safe_drop_index(op.f('ix_team_provider_mappings_source'), table_name='team_provider_mappings')
    _safe_drop_index(op.f('ix_team_provider_mappings_normalized_name'), table_name='team_provider_mappings')
    _safe_create_index(op.f('ix_team_mapping_team'), 'team_provider_mappings', ['team_id'], unique=False)
    _safe_create_index(op.f('ix_team_mapping_source'), 'team_provider_mappings', ['source'], unique=False)
    _safe_create_index(op.f('ix_team_mapping_norm'), 'team_provider_mappings', ['normalized_name'], unique=False)
    _safe_drop_index(op.f('ix_standings_team_id'), table_name='standings')
    _safe_drop_index(op.f('ix_standings_league_id'), table_name='standings')
    _safe_create_index(op.f('ix_standings_league'), 'standings', ['league_id'], unique=False)
    _safe_drop_index(op.f('ix_source_conflicts_status'), table_name='source_conflicts')
    _safe_drop_index(op.f('ix_source_conflicts_match_id'), table_name='source_conflicts')
    _safe_create_index(op.f('ix_conflict_status'), 'source_conflicts', ['status'], unique=False)
    _safe_create_index(op.f('ix_conflict_match'), 'source_conflicts', ['match_id'], unique=False)
    _safe_drop_index(op.f('ix_raw_data_records_temporal_quality'), table_name='raw_data_records')
    _safe_drop_index(op.f('ix_raw_data_records_source'), table_name='raw_data_records')
    _safe_drop_index(op.f('ix_raw_data_records_retrieved_at'), table_name='raw_data_records')
    _safe_drop_index(op.f('ix_raw_data_records_processing_status'), table_name='raw_data_records')
    _safe_drop_index(op.f('ix_raw_data_records_entity_type'), table_name='raw_data_records')
    _safe_create_index(op.f('ix_raw_temporal'), 'raw_data_records', ['temporal_quality'], unique=False)
    _safe_create_index(op.f('ix_raw_status'), 'raw_data_records', ['processing_status'], unique=False)
    _safe_create_index(op.f('ix_raw_source'), 'raw_data_records', ['source'], unique=False)
    _safe_create_index(op.f('ix_raw_retrieved'), 'raw_data_records', ['retrieved_at'], unique=False)
    _safe_create_index(op.f('ix_raw_entity'), 'raw_data_records', ['entity_type'], unique=False)
    _safe_drop_index(op.f('ix_provider_request_logs_timestamp'), table_name='provider_request_logs')
    _safe_drop_index(op.f('ix_provider_request_logs_provider'), table_name='provider_request_logs')
    _safe_create_index(op.f('ix_reqlog_ts'), 'provider_request_logs', ['timestamp'], unique=False)
    _safe_create_index(op.f('ix_reqlog_provider'), 'provider_request_logs', ['provider'], unique=False)
    _safe_drop_index(op.f('ix_predictions_prediction_timestamp'), table_name='predictions')
    _safe_drop_index(op.f('ix_predictions_model_name'), table_name='predictions')
    _safe_drop_index(op.f('ix_predictions_match_id'), table_name='predictions')
    _safe_create_index(op.f('ix_predictions_model'), 'predictions', ['model_name'], unique=False)
    _safe_create_index(op.f('ix_predictions_match'), 'predictions', ['match_id'], unique=False)
    _safe_drop_index(op.f('ix_prediction_results_prediction_id'), table_name='prediction_results')
    _safe_drop_index(op.f('ix_player_provider_mappings_team_id'), table_name='player_provider_mappings')
    _safe_drop_index(op.f('ix_player_provider_mappings_source'), table_name='player_provider_mappings')
    _safe_drop_index(op.f('ix_player_provider_mappings_player_id'), table_name='player_provider_mappings')
    _safe_drop_index(op.f('ix_player_provider_mappings_normalized_name'), table_name='player_provider_mappings')
    _safe_create_index(op.f('ix_player_mapping_source'), 'player_provider_mappings', ['source'], unique=False)
    _safe_create_index(op.f('ix_player_mapping_player'), 'player_provider_mappings', ['player_id'], unique=False)
    _safe_create_index(op.f('ix_player_mapping_norm'), 'player_provider_mappings', ['normalized_name'], unique=False)
    _safe_drop_index(op.f('ix_odds_snapshots_timestamp'), table_name='odds_snapshots')
    _safe_drop_index(op.f('ix_odds_snapshots_match_id'), table_name='odds_snapshots')
    _safe_drop_index(op.f('ix_odds_snapshots_market_type'), table_name='odds_snapshots')
    _safe_create_index(op.f('ix_odds_snapshots_ts'), 'odds_snapshots', ['timestamp'], unique=False)
    _safe_create_index(op.f('ix_odds_snapshots_match_market_time'), 'odds_snapshots', ['match_id', 'market_type', 'timestamp'], unique=False)
    _safe_create_index(op.f('ix_odds_snapshots_match_bookmaker_market'), 'odds_snapshots', ['match_id', 'bookmaker_id', 'market_type'], unique=False)
    _safe_create_index(op.f('ix_odds_snapshots_match'), 'odds_snapshots', ['match_id'], unique=False)
    _safe_drop_index(op.f('ix_odds_selections_snapshot_id'), table_name='odds_selections')
    _safe_drop_index(op.f('ix_odds_selections_dedup_hash'), table_name='odds_selections')
    _safe_create_index(op.f('ix_odds_selections_snap'), 'odds_selections', ['snapshot_id'], unique=False)
    _safe_drop_index(op.f('ix_model_training_runs_model_name'), table_name='model_training_runs')
    _safe_create_index(op.f('ix_training_runs_model'), 'model_training_runs', ['model_name'], unique=False)
    _safe_drop_index(op.f('ix_model_evaluations_training_run_id'), table_name='model_evaluations')
    _safe_drop_index(op.f('ix_model_evaluations_model_name'), table_name='model_evaluations')
    _safe_create_index(op.f('ix_model_evaluations_model'), 'model_evaluations', ['model_name'], unique=False)
    _safe_drop_index(op.f('ix_matches_kickoff_at'), table_name='matches')
    _safe_create_index(op.f('ix_matches_kickoff'), 'matches', ['kickoff_at'], unique=False)
    _safe_drop_index(op.f('ix_match_statistics_match_id'), table_name='match_statistics')
    _safe_create_index(op.f('ix_match_statistics_match'), 'match_statistics', ['match_id'], unique=False)
    _safe_drop_index(op.f('ix_match_source_mappings_source'), table_name='match_source_mappings')
    _safe_drop_index(op.f('ix_match_source_mappings_match_id'), table_name='match_source_mappings')
    _safe_create_index(op.f('ix_match_mapping_source'), 'match_source_mappings', ['source'], unique=False)
    _safe_create_index(op.f('ix_match_mapping_match'), 'match_source_mappings', ['match_id'], unique=False)
    _safe_drop_index(op.f('ix_match_events_match_id'), table_name='match_events')
    _safe_create_index(op.f('ix_match_events_match'), 'match_events', ['match_id'], unique=False)
    _safe_drop_index(op.f('ix_lineups_match_id'), table_name='lineups')
    _safe_create_index(op.f('ix_lineups_match'), 'lineups', ['match_id'], unique=False)
    _safe_drop_index(op.f('ix_leagues_code'), table_name='leagues')
    _safe_create_index(op.f('ix_leagues_code'), 'leagues', ['code'], unique=False)
    _safe_drop_index(op.f('ix_data_sync_logs_provider'), table_name='data_sync_logs')
    _safe_create_index(op.f('ix_sync_provider'), 'data_sync_logs', ['provider'], unique=False)
    _safe_drop_index(op.f('ix_backtest_runs_model_name'), table_name='backtest_runs')
    _safe_create_index(op.f('ix_backtest_runs_model'), 'backtest_runs', ['model_name'], unique=False)
    _safe_drop_index(op.f('ix_prediction_diffs_match_id'), table_name='prediction_diffs')
    _safe_drop_table('prediction_diffs')
    _safe_drop_index(op.f('ix_scenario_runs_status'), table_name='scenario_runs')
    _safe_drop_index(op.f('ix_scenario_runs_prediction_id'), table_name='scenario_runs')
    _safe_drop_index(op.f('ix_scenario_runs_match_id'), table_name='scenario_runs')
    _safe_drop_table('scenario_runs')
    _safe_drop_index(op.f('ix_prediction_versions_state'), table_name='prediction_versions')
    _safe_drop_index(op.f('ix_prediction_versions_prediction_id'), table_name='prediction_versions')
    _safe_drop_index(op.f('ix_prediction_versions_match_id'), table_name='prediction_versions')
    _safe_drop_index('ix_prediction_versions_match_cutoff', table_name='prediction_versions')
    _safe_drop_index('ix_prediction_versions_match_created', table_name='prediction_versions')
    _safe_drop_table('prediction_versions')
    _safe_drop_index(op.f('ix_prediction_explanations_status'), table_name='prediction_explanations')
    _safe_drop_index(op.f('ix_prediction_explanations_prediction_id'), table_name='prediction_explanations')
    _safe_drop_index(op.f('ix_prediction_explanations_match_id'), table_name='prediction_explanations')
    _safe_drop_table('prediction_explanations')
    _safe_drop_index(op.f('ix_prediction_evaluations_prediction_id'), table_name='prediction_evaluations')
    _safe_drop_index(op.f('ix_prediction_evaluations_match_id'), table_name='prediction_evaluations')
    _safe_drop_table('prediction_evaluations')
    _safe_drop_index(op.f('ix_player_feature_provenance_snapshot_id'), table_name='player_feature_provenance')
    _safe_drop_index(op.f('ix_player_feature_provenance_feature_name'), table_name='player_feature_provenance')
    _safe_drop_table('player_feature_provenance')
    _safe_drop_index(op.f('ix_mirofish_runs_status'), table_name='mirofish_runs')
    _safe_drop_index(op.f('ix_mirofish_runs_prediction_id'), table_name='mirofish_runs')
    _safe_drop_index(op.f('ix_mirofish_runs_match_id'), table_name='mirofish_runs')
    _safe_drop_table('mirofish_runs')
    _safe_drop_index(op.f('ix_intelligence_snapshots_snapshot_id'), table_name='intelligence_snapshots')
    _safe_drop_index(op.f('ix_intelligence_snapshots_payload_hash'), table_name='intelligence_snapshots')
    _safe_drop_index(op.f('ix_intelligence_snapshots_match_id'), table_name='intelligence_snapshots')
    _safe_drop_table('intelligence_snapshots')
    _safe_drop_index(op.f('ix_analogue_results_status'), table_name='analogue_results')
    _safe_drop_index(op.f('ix_analogue_results_prediction_id'), table_name='analogue_results')
    _safe_drop_index(op.f('ix_analogue_results_match_id'), table_name='analogue_results')
    _safe_drop_table('analogue_results')
    _safe_drop_index(op.f('ix_player_team_memberships_team_id'), table_name='player_team_memberships')
    _safe_drop_index(op.f('ix_player_team_memberships_player_id'), table_name='player_team_memberships')
    _safe_drop_index('ix_membership_player_team', table_name='player_team_memberships')
    _safe_drop_table('player_team_memberships')
    _safe_drop_index('ix_player_snap_match_cutoff', table_name='player_feature_snapshots')
    _safe_drop_index(op.f('ix_player_feature_snapshots_payload_hash'), table_name='player_feature_snapshots')
    _safe_drop_index(op.f('ix_player_feature_snapshots_match_id'), table_name='player_feature_snapshots')
    _safe_drop_table('player_feature_snapshots')
    _safe_drop_index(op.f('ix_mirofish_scenario_runs_status'), table_name='mirofish_scenario_runs')
    _safe_drop_index(op.f('ix_mirofish_scenario_runs_scenario_id'), table_name='mirofish_scenario_runs')
    _safe_drop_index(op.f('ix_mirofish_scenario_runs_request_hash'), table_name='mirofish_scenario_runs')
    _safe_drop_index(op.f('ix_mirofish_scenario_runs_match_id'), table_name='mirofish_scenario_runs')
    _safe_drop_index(op.f('ix_mirofish_scenario_runs_intelligence_snapshot_id'), table_name='mirofish_scenario_runs')
    _safe_drop_table('mirofish_scenario_runs')
    _safe_drop_index(op.f('ix_match_observations_source'), table_name='match_observations')
    _safe_drop_index(op.f('ix_match_observations_match_id'), table_name='match_observations')
    _safe_drop_index('ix_match_obs_match_field', table_name='match_observations')
    _safe_drop_table('match_observations')
    _safe_drop_index(op.f('ix_unresolved_records_status'), table_name='unresolved_records')
    _safe_drop_index(op.f('ix_unresolved_records_entity_type'), table_name='unresolved_records')
    _safe_drop_index(op.f('ix_unresolved_records_dedup_key'), table_name='unresolved_records')
    _safe_drop_table('unresolved_records')
    _safe_drop_index(op.f('ix_stat_definitions_source'), table_name='stat_definitions')
    _safe_drop_index(op.f('ix_stat_definitions_metric_name'), table_name='stat_definitions')
    _safe_drop_table('stat_definitions')
    _safe_drop_index(op.f('ix_source_qualifications_status'), table_name='source_qualifications')
    _safe_drop_index(op.f('ix_source_qualifications_source'), table_name='source_qualifications')
    _safe_drop_index(op.f('ix_source_qualifications_qualification_run_id'), table_name='source_qualifications')
    _safe_drop_table('source_qualifications')
    _safe_drop_index(op.f('ix_source_health_state'), table_name='source_health')
    _safe_drop_index('ix_source_health_source_fetched', table_name='source_health')
    _safe_drop_index(op.f('ix_source_health_source'), table_name='source_health')
    _safe_drop_table('source_health')
    _safe_drop_index(op.f('ix_source_activations_state'), table_name='source_activations')
    _safe_drop_index(op.f('ix_source_activations_source'), table_name='source_activations')
    _safe_drop_table('source_activations')
    _safe_drop_index(op.f('ix_research_models_status'), table_name='research_models')
    _safe_drop_index(op.f('ix_research_models_model_id'), table_name='research_models')
    _safe_drop_index(op.f('ix_research_models_artifact_hash'), table_name='research_models')
    _safe_drop_table('research_models')
    _safe_drop_index(op.f('ix_reconciliation_conflicts_severity'), table_name='reconciliation_conflicts')
    _safe_drop_index(op.f('ix_reconciliation_conflicts_resolution_status'), table_name='reconciliation_conflicts')
    _safe_drop_index(op.f('ix_reconciliation_conflicts_entity_type'), table_name='reconciliation_conflicts')
    _safe_drop_index(op.f('ix_reconciliation_conflicts_dedup_key'), table_name='reconciliation_conflicts')
    _safe_drop_index(op.f('ix_reconciliation_conflicts_canonical_entity_id'), table_name='reconciliation_conflicts')
    _safe_drop_index('ix_recon_conflict_entity', table_name='reconciliation_conflicts')
    _safe_drop_table('reconciliation_conflicts')
    _safe_drop_index(op.f('ix_manual_mappings_entity_type'), table_name='manual_mappings')
    _safe_drop_index(op.f('ix_manual_mappings_canonical_entity_id'), table_name='manual_mappings')
    _safe_drop_table('manual_mappings')
    _safe_drop_index(op.f('ix_canonical_field_versions_entity_type'), table_name='canonical_field_versions')
    _safe_drop_index(op.f('ix_canonical_field_versions_canonical_entity_id'), table_name='canonical_field_versions')
    _safe_drop_index('ix_canon_version_entity', table_name='canonical_field_versions')
    _safe_drop_table('canonical_field_versions')
    _safe_drop_index(op.f('ix_acquisition_runs_status'), table_name='acquisition_runs')
    _safe_drop_index(op.f('ix_acquisition_runs_source'), table_name='acquisition_runs')
    _safe_drop_index(op.f('ix_acquisition_runs_run_id'), table_name='acquisition_runs')
    _safe_drop_index('ix_acq_runs_source_started', table_name='acquisition_runs')
    _safe_drop_table('acquisition_runs')
    _safe_drop_index(op.f('ix_acquisition_jobs_name'), table_name='acquisition_jobs')
    _safe_drop_table('acquisition_jobs')
    _safe_drop_index(op.f('ix_acquisition_job_records_status'), table_name='acquisition_job_records')
    _safe_drop_index(op.f('ix_acquisition_job_records_source'), table_name='acquisition_job_records')
    _safe_drop_index(op.f('ix_acquisition_job_records_job_type'), table_name='acquisition_job_records')
    _safe_drop_index(op.f('ix_acquisition_job_records_job_id'), table_name='acquisition_job_records')
    _safe_drop_index(op.f('ix_acquisition_job_records_competition'), table_name='acquisition_job_records')
    _safe_drop_index('ix_acq_job_records_type_status', table_name='acquisition_job_records')
    _safe_drop_index('ix_acq_job_records_competition', table_name='acquisition_job_records')
    _safe_drop_table('acquisition_job_records')
    _safe_drop_index(op.f('ix_acquisition_job_locks_lock_key'), table_name='acquisition_job_locks')
    _safe_drop_table('acquisition_job_locks')
    # ### end Alembic commands ###
